#!/usr/bin/env bash

set -e

code-insiders --install-extension 13xforever.language-x86-64-assembly --pre-release
code-insiders --install-extension adam-bender.commit-message-editor --pre-release
code-insiders --install-extension albert.tabout --pre-release
code-insiders --install-extension angular.ng-template --pre-release
code-insiders --install-extension basdp.language-gas-x86 --pre-release
code-insiders --install-extension batisteo.vscode-django --pre-release
code-insiders --install-extension bbenoist.nix --pre-release
code-insiders --install-extension bdavs.expect --pre-release
code-insiders --install-extension bierner.lit-html --pre-release
code-insiders --install-extension bmewburn.vscode-intelephense-client --pre-release
code-insiders --install-extension boyswan.glsl-literal --pre-release
code-insiders --install-extension celianriboulet.webvalidator --pre-release
code-insiders --install-extension christian-kohler.npm-intellisense --pre-release
code-insiders --install-extension christian-kohler.path-intellisense --pre-release
code-insiders --install-extension codezombiech.gitignore --pre-release
code-insiders --install-extension colton.inline-html --pre-release
code-insiders --install-extension cschlosser.doxdocgen --pre-release
code-insiders --install-extension davidanson.vscode-markdownlint --pre-release
code-insiders --install-extension dbaeumer.vscode-eslint --pre-release
code-insiders --install-extension devkir.elixir-syntax-vscode --pre-release
code-insiders --install-extension dmitry-korobchenko.prototxt --pre-release
code-insiders --install-extension donjayamanne.githistory --pre-release
code-insiders --install-extension donjayamanne.python-environment-manager --pre-release
code-insiders --install-extension donjayamanne.python-extension-pack --pre-release
code-insiders --install-extension dtsvet.vscode-wasm --pre-release
code-insiders --install-extension dustypomerleau.rust-syntax --pre-release
code-insiders --install-extension eamodio.gitlens --pre-release
code-insiders --install-extension editorconfig.editorconfig --pre-release
code-insiders --install-extension esbenp.prettier-vscode --pre-release
code-insiders --install-extension formulahendry.code-runner --pre-release
code-insiders --install-extension foxundermoon.shell-format --pre-release
code-insiders --install-extension fredrikbakke.agda-syntax --pre-release
code-insiders --install-extension geforcelegend.vscode-glsl --pre-release
code-insiders --install-extension gimly81.fortran --pre-release
code-insiders --install-extension github.codespaces --pre-release
code-insiders --install-extension github.copilot --pre-release
code-insiders --install-extension github.copilot-chat --pre-release
code-insiders --install-extension github.remotehub --pre-release
code-insiders --install-extension github.vscode-pull-request-github --pre-release
code-insiders --install-extension gruntfuggly.todo-tree --pre-release
code-insiders --install-extension guyskk.language-cython --pre-release
code-insiders --install-extension howardzuo.vscode-git-tags --pre-release
code-insiders --install-extension humao.rest-client --pre-release
code-insiders --install-extension idleberg.applescript --pre-release
code-insiders --install-extension jakebathman.mysql-syntax --pre-release
code-insiders --install-extension jbockle.jbockle-format-files --pre-release
code-insiders --install-extension jeff-hykin.better-c-syntax --pre-release
code-insiders --install-extension jeff-hykin.better-cpp-syntax --pre-release
code-insiders --install-extension jeff-hykin.better-csv-syntax --pre-release
code-insiders --install-extension jeff-hykin.better-dockerfile-syntax --pre-release
code-insiders --install-extension jeff-hykin.better-go-syntax --pre-release
code-insiders --install-extension jeff-hykin.better-js-syntax --pre-release
code-insiders --install-extension jeff-hykin.better-lisp-syntax --pre-release
code-insiders --install-extension jeff-hykin.better-objc-syntax --pre-release
code-insiders --install-extension jeff-hykin.better-objcpp-syntax --pre-release
code-insiders --install-extension jeff-hykin.better-perl-syntax --pre-release
code-insiders --install-extension jeff-hykin.better-prolog-syntax --pre-release
code-insiders --install-extension jeff-hykin.better-shellscript-syntax --pre-release
code-insiders --install-extension jeff-hykin.better-syntax --pre-release
code-insiders --install-extension jep-a.lua-plus --pre-release
code-insiders --install-extension johnpapa.vscode-peacock --pre-release
code-insiders --install-extension jonwolfe.language-polymer --pre-release
code-insiders --install-extension justusadam.language-haskell --pre-release
code-insiders --install-extension karunamurti.haml --pre-release
code-insiders --install-extension kennethceyer.io --pre-release
code-insiders --install-extension kevinrose.vsc-python-indent --pre-release
code-insiders --install-extension ldez.ignore-files --pre-release
code-insiders --install-extension mads-hartmann.bash-ide-vscode --pre-release
code-insiders --install-extension magicstack.magicpython --pre-release
code-insiders --install-extension mariomatheu.syntax-project-pbxproj --pre-release
code-insiders --install-extension mechatroner.rainbow-csv --pre-release
code-insiders --install-extension mhutchie.git-graph --pre-release
code-insiders --install-extension mkhl.direnv --pre-release
code-insiders --install-extension ms-azuretools.vscode-docker --pre-release
code-insiders --install-extension ms-dotnettools.csdevkit --pre-release
code-insiders --install-extension ms-dotnettools.csharp --pre-release
code-insiders --install-extension ms-dotnettools.vscode-dotnet-runtime --pre-release
code-insiders --install-extension ms-dotnettools.vscodeintellicode-csharp --pre-release
code-insiders --install-extension ms-edgedevtools.vscode-edge-devtools --pre-release
code-insiders --install-extension ms-kubernetes-tools.vscode-kubernetes-tools --pre-release
code-insiders --install-extension ms-python.black-formatter --pre-release
code-insiders --install-extension ms-python.debugpy --pre-release
code-insiders --install-extension ms-python.python --pre-release
code-insiders --install-extension ms-python.vscode-pylance --pre-release
code-insiders --install-extension ms-toolsai.jupyter --pre-release
code-insiders --install-extension ms-toolsai.jupyter-keymap --pre-release
code-insiders --install-extension ms-toolsai.jupyter-renderers --pre-release
code-insiders --install-extension ms-toolsai.vscode-jupyter-cell-tags --pre-release
code-insiders --install-extension ms-toolsai.vscode-jupyter-slideshow --pre-release
code-insiders --install-extension ms-vscode-remote.remote-containers --pre-release
code-insiders --install-extension ms-vscode-remote.remote-ssh --pre-release
code-insiders --install-extension ms-vscode-remote.remote-ssh-edit --pre-release
code-insiders --install-extension ms-vscode-remote.remote-wsl --pre-release
code-insiders --install-extension ms-vscode-remote.vscode-remote-extensionpack --pre-release
code-insiders --install-extension ms-vscode.azure-repos --pre-release
code-insiders --install-extension ms-vscode.azurecli --pre-release
code-insiders --install-extension ms-vscode.cmake-tools --pre-release
code-insiders --install-extension ms-vscode.cpptools --pre-release
code-insiders --install-extension ms-vscode.cpptools-extension-pack --pre-release
code-insiders --install-extension ms-vscode.cpptools-themes --pre-release
code-insiders --install-extension ms-vscode.live-server --pre-release
code-insiders --install-extension ms-vscode.powershell --pre-release
code-insiders --install-extension ms-vscode.remote-explorer --pre-release
code-insiders --install-extension ms-vscode.remote-repositories --pre-release
code-insiders --install-extension ms-vscode.remote-server --pre-release
code-insiders --install-extension msjsdiag.vscode-react-native --pre-release
code-insiders --install-extension neo4j-extensions.neo4j-for-vscode --pre-release
code-insiders --install-extension njpwerner.autodocstring --pre-release
code-insiders --install-extension oderwat.indent-rainbow --pre-release
code-insiders --install-extension okteto.remote-kubernetes --pre-release
code-insiders --install-extension oscarcs.dart-syntax-highlighting-only --pre-release
code-insiders --install-extension pinage404.bash-extension-pack --pre-release
code-insiders --install-extension pkief.material-icon-theme --pre-release
code-insiders --install-extension radium-v.better-less --pre-release
code-insiders --install-extension redcmd.tmlanguage-syntax-highlighter --pre-release
code-insiders --install-extension redhat.java --pre-release
code-insiders --install-extension redhat.vscode-community-server-connector --pre-release
code-insiders --install-extension redhat.vscode-rsp-ui --pre-release
code-insiders --install-extension redhat.vscode-xml --pre-release
code-insiders --install-extension redhat.vscode-yaml --pre-release
code-insiders --install-extension rogalmic.bash-debug --pre-release
code-insiders --install-extension rpinski.shebang-snippets --pre-release
code-insiders --install-extension rust-lang.rust-analyzer --pre-release
code-insiders --install-extension scala-lang.scala --pre-release
code-insiders --install-extension shopify.ruby-lsp --pre-release
code-insiders --install-extension sidneys1.gitconfig --pre-release
code-insiders --install-extension slevesque.shader --pre-release
code-insiders --install-extension sonarsource.sonarlint-vscode --pre-release
code-insiders --install-extension spmeesseman.vscode-taskexplorer --pre-release
code-insiders --install-extension streetsidesoftware.code-spell-checker --pre-release
code-insiders --install-extension syler.sass-indented --pre-release
code-insiders --install-extension tamasfe.even-better-toml --pre-release
code-insiders --install-extension timonwong.shellcheck --pre-release
code-insiders --install-extension toasty-technologies.octave --pre-release
code-insiders --install-extension tomwhite007.rename-angular-component --pre-release
code-insiders --install-extension vinirossa.vscode-gitandgithub-pack --pre-release
code-insiders --install-extension visualstudioexptteam.intellicode-api-usage-examples --pre-release
code-insiders --install-extension visualstudioexptteam.vscodeintellicode --pre-release
code-insiders --install-extension vmware.vscode-boot-dev-pack --pre-release
code-insiders --install-extension vmware.vscode-spring-boot --pre-release
code-insiders --install-extension vscjava.vscode-gradle --pre-release
code-insiders --install-extension vscjava.vscode-java-debug --pre-release
code-insiders --install-extension vscjava.vscode-java-dependency --pre-release
code-insiders --install-extension vscjava.vscode-java-pack --pre-release
code-insiders --install-extension vscjava.vscode-java-test --pre-release
code-insiders --install-extension vscjava.vscode-maven --pre-release
code-insiders --install-extension vscjava.vscode-spring-boot-dashboard --pre-release
code-insiders --install-extension vscjava.vscode-spring-initializr --pre-release
code-insiders --install-extension wayou.vscode-todo-highlight --pre-release
code-insiders --install-extension wholroyd.jinja --pre-release
code-insiders --install-extension wmaurer.change-case --pre-release
code-insiders --install-extension yuce.erlang-otp --pre-release
code-insiders --install-extension ziyasal.vscode-open-in-github --pre-release
