#!/usr/bin/env bash

set -e

code --install-extension 13xforever.language-x86-64-assembly
code --install-extension adam-bender.commit-message-editor
code --install-extension albert.tabout
code --install-extension angular.ng-template
code --install-extension basdp.language-gas-x86
code --install-extension batisteo.vscode-django
code --install-extension bbenoist.nix
code --install-extension bdavs.expect
code --install-extension bierner.lit-html
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension boyswan.glsl-literal
code --install-extension celianriboulet.webvalidator
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension colton.inline-html
code --install-extension cschlosser.doxdocgen
code --install-extension davidanson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension devkir.elixir-syntax-vscode
code --install-extension dmitry-korobchenko.prototxt
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.python-environment-manager
code --install-extension donjayamanne.python-extension-pack
code --install-extension dtsvet.vscode-wasm
code --install-extension dustypomerleau.rust-syntax
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension foxundermoon.shell-format
code --install-extension fredrikbakke.agda-syntax
code --install-extension geforcelegend.vscode-glsl
code --install-extension gimly81.fortran
code --install-extension github.codespaces
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.remotehub
code --install-extension github.vscode-pull-request-github
code --install-extension gruntfuggly.todo-tree
code --install-extension guyskk.language-cython
code --install-extension howardzuo.vscode-git-tags
code --install-extension humao.rest-client
code --install-extension idleberg.applescript
code --install-extension jakebathman.mysql-syntax
code --install-extension jbockle.jbockle-format-files
code --install-extension jeff-hykin.better-c-syntax
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension jeff-hykin.better-csv-syntax
code --install-extension jeff-hykin.better-dockerfile-syntax
code --install-extension jeff-hykin.better-go-syntax
code --install-extension jeff-hykin.better-js-syntax
code --install-extension jeff-hykin.better-lisp-syntax
code --install-extension jeff-hykin.better-objc-syntax
code --install-extension jeff-hykin.better-objcpp-syntax
code --install-extension jeff-hykin.better-perl-syntax
code --install-extension jeff-hykin.better-prolog-syntax
code --install-extension jeff-hykin.better-shellscript-syntax
code --install-extension jeff-hykin.better-syntax
code --install-extension jep-a.lua-plus
code --install-extension johnpapa.vscode-peacock
code --install-extension jonwolfe.language-polymer
code --install-extension justusadam.language-haskell
code --install-extension karunamurti.haml
code --install-extension kennethceyer.io
code --install-extension kevinrose.vsc-python-indent
code --install-extension ldez.ignore-files
code --install-extension mads-hartmann.bash-ide-vscode
code --install-extension magicstack.magicpython
code --install-extension mariomatheu.syntax-project-pbxproj
code --install-extension mechatroner.rainbow-csv
code --install-extension mhutchie.git-graph
code --install-extension mkhl.direnv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csdevkit
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-dotnettools.vscodeintellicode-csharp
code --install-extension ms-edgedevtools.vscode-edge-devtools
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.azure-repos
code --install-extension ms-vscode.azurecli
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.live-server
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-repositories
code --install-extension ms-vscode.remote-server
code --install-extension msjsdiag.vscode-react-native
code --install-extension neo4j-extensions.neo4j-for-vscode
code --install-extension njpwerner.autodocstring
code --install-extension oderwat.indent-rainbow
code --install-extension okteto.remote-kubernetes
code --install-extension oscarcs.dart-syntax-highlighting-only
code --install-extension pinage404.bash-extension-pack
code --install-extension pkief.material-icon-theme
code --install-extension radium-v.better-less
code --install-extension redcmd.tmlanguage-syntax-highlighter
code --install-extension redhat.java
code --install-extension redhat.vscode-community-server-connector
code --install-extension redhat.vscode-rsp-ui
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension rogalmic.bash-debug
code --install-extension rpinski.shebang-snippets
code --install-extension rust-lang.rust-analyzer
code --install-extension scala-lang.scala
code --install-extension shopify.ruby-lsp
code --install-extension sidneys1.gitconfig
code --install-extension slevesque.shader
code --install-extension sonarsource.sonarlint-vscode
code --install-extension spmeesseman.vscode-taskexplorer
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension syler.sass-indented
code --install-extension tamasfe.even-better-toml
code --install-extension timonwong.shellcheck
code --install-extension toasty-technologies.octave
code --install-extension tomwhite007.rename-angular-component
code --install-extension vinirossa.vscode-gitandgithub-pack
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vmware.vscode-boot-dev-pack
code --install-extension vmware.vscode-spring-boot
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-boot-dashboard
code --install-extension vscjava.vscode-spring-initializr
code --install-extension wayou.vscode-todo-highlight
code --install-extension wholroyd.jinja
code --install-extension wmaurer.change-case
code --install-extension yuce.erlang-otp
code --install-extension ziyasal.vscode-open-in-github
