#!/usr/bin/env bash

set -e

code-insiders --install-extension 13xforever.language-x86-64-assembly
code-insiders --install-extension adam-bender.commit-message-editor
code-insiders --install-extension albert.tabout
code-insiders --install-extension angular.ng-template
code-insiders --install-extension basdp.language-gas-x86
code-insiders --install-extension batisteo.vscode-django
code-insiders --install-extension bbenoist.nix
code-insiders --install-extension bdavs.expect
code-insiders --install-extension bierner.lit-html
code-insiders --install-extension bmewburn.vscode-intelephense-client
code-insiders --install-extension boyswan.glsl-literal
code-insiders --install-extension celianriboulet.webvalidator
code-insiders --install-extension christian-kohler.npm-intellisense
code-insiders --install-extension christian-kohler.path-intellisense
code-insiders --install-extension codezombiech.gitignore
code-insiders --install-extension colton.inline-html
code-insiders --install-extension cschlosser.doxdocgen
code-insiders --install-extension davidanson.vscode-markdownlint
code-insiders --install-extension dbaeumer.vscode-eslint
code-insiders --install-extension devkir.elixir-syntax-vscode
code-insiders --install-extension dmitry-korobchenko.prototxt
code-insiders --install-extension donjayamanne.githistory
code-insiders --install-extension donjayamanne.python-environment-manager
code-insiders --install-extension donjayamanne.python-extension-pack
code-insiders --install-extension dtsvet.vscode-wasm
code-insiders --install-extension dustypomerleau.rust-syntax
code-insiders --install-extension eamodio.gitlens
code-insiders --install-extension editorconfig.editorconfig
code-insiders --install-extension esbenp.prettier-vscode
code-insiders --install-extension formulahendry.code-runner
code-insiders --install-extension foxundermoon.shell-format
code-insiders --install-extension fredrikbakke.agda-syntax
code-insiders --install-extension geforcelegend.vscode-glsl
code-insiders --install-extension gimly81.fortran
code-insiders --install-extension github.codespaces
code-insiders --install-extension github.copilot
code-insiders --install-extension github.copilot-chat
code-insiders --install-extension github.remotehub
code-insiders --install-extension github.vscode-pull-request-github
code-insiders --install-extension gruntfuggly.todo-tree
code-insiders --install-extension guyskk.language-cython
code-insiders --install-extension howardzuo.vscode-git-tags
code-insiders --install-extension humao.rest-client
code-insiders --install-extension idleberg.applescript
code-insiders --install-extension jakebathman.mysql-syntax
code-insiders --install-extension jbockle.jbockle-format-files
code-insiders --install-extension jeff-hykin.better-c-syntax
code-insiders --install-extension jeff-hykin.better-cpp-syntax
code-insiders --install-extension jeff-hykin.better-csv-syntax
code-insiders --install-extension jeff-hykin.better-dockerfile-syntax
code-insiders --install-extension jeff-hykin.better-go-syntax
code-insiders --install-extension jeff-hykin.better-js-syntax
code-insiders --install-extension jeff-hykin.better-lisp-syntax
code-insiders --install-extension jeff-hykin.better-objc-syntax
code-insiders --install-extension jeff-hykin.better-objcpp-syntax
code-insiders --install-extension jeff-hykin.better-perl-syntax
code-insiders --install-extension jeff-hykin.better-prolog-syntax
code-insiders --install-extension jeff-hykin.better-shellscript-syntax
code-insiders --install-extension jeff-hykin.better-syntax
code-insiders --install-extension jep-a.lua-plus
code-insiders --install-extension johnpapa.vscode-peacock
code-insiders --install-extension jonwolfe.language-polymer
code-insiders --install-extension justusadam.language-haskell
code-insiders --install-extension karunamurti.haml
code-insiders --install-extension kennethceyer.io
code-insiders --install-extension kevinrose.vsc-python-indent
code-insiders --install-extension ldez.ignore-files
code-insiders --install-extension mads-hartmann.bash-ide-vscode
code-insiders --install-extension magicstack.magicpython
code-insiders --install-extension mariomatheu.syntax-project-pbxproj
code-insiders --install-extension mechatroner.rainbow-csv
code-insiders --install-extension mhutchie.git-graph
code-insiders --install-extension mkhl.direnv
code-insiders --install-extension ms-azuretools.vscode-docker
code-insiders --install-extension ms-dotnettools.csdevkit
code-insiders --install-extension ms-dotnettools.csharp
code-insiders --install-extension ms-dotnettools.vscode-dotnet-runtime
code-insiders --install-extension ms-dotnettools.vscodeintellicode-csharp
code-insiders --install-extension ms-edgedevtools.vscode-edge-devtools
code-insiders --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code-insiders --install-extension ms-python.black-formatter
code-insiders --install-extension ms-python.debugpy
code-insiders --install-extension ms-python.python
code-insiders --install-extension ms-python.vscode-pylance
code-insiders --install-extension ms-toolsai.jupyter
code-insiders --install-extension ms-toolsai.jupyter-keymap
code-insiders --install-extension ms-toolsai.jupyter-renderers
code-insiders --install-extension ms-toolsai.vscode-jupyter-cell-tags
code-insiders --install-extension ms-toolsai.vscode-jupyter-slideshow
code-insiders --install-extension ms-vscode-remote.remote-containers
code-insiders --install-extension ms-vscode-remote.remote-ssh
code-insiders --install-extension ms-vscode-remote.remote-ssh-edit
code-insiders --install-extension ms-vscode-remote.remote-wsl
code-insiders --install-extension ms-vscode-remote.vscode-remote-extensionpack
code-insiders --install-extension ms-vscode.azure-repos
code-insiders --install-extension ms-vscode.azurecli
code-insiders --install-extension ms-vscode.cmake-tools
code-insiders --install-extension ms-vscode.cpptools
code-insiders --install-extension ms-vscode.cpptools-extension-pack
code-insiders --install-extension ms-vscode.cpptools-themes
code-insiders --install-extension ms-vscode.live-server
code-insiders --install-extension ms-vscode.powershell
code-insiders --install-extension ms-vscode.remote-explorer
code-insiders --install-extension ms-vscode.remote-repositories
code-insiders --install-extension ms-vscode.remote-server
code-insiders --install-extension msjsdiag.vscode-react-native
code-insiders --install-extension neo4j-extensions.neo4j-for-vscode
code-insiders --install-extension njpwerner.autodocstring
code-insiders --install-extension oderwat.indent-rainbow
code-insiders --install-extension okteto.remote-kubernetes
code-insiders --install-extension oscarcs.dart-syntax-highlighting-only
code-insiders --install-extension pinage404.bash-extension-pack
code-insiders --install-extension pkief.material-icon-theme
code-insiders --install-extension radium-v.better-less
code-insiders --install-extension redcmd.tmlanguage-syntax-highlighter
code-insiders --install-extension redhat.java
code-insiders --install-extension redhat.vscode-community-server-connector
code-insiders --install-extension redhat.vscode-rsp-ui
code-insiders --install-extension redhat.vscode-xml
code-insiders --install-extension redhat.vscode-yaml
code-insiders --install-extension rogalmic.bash-debug
code-insiders --install-extension rpinski.shebang-snippets
code-insiders --install-extension rust-lang.rust-analyzer
code-insiders --install-extension scala-lang.scala
code-insiders --install-extension shopify.ruby-lsp
code-insiders --install-extension sidneys1.gitconfig
code-insiders --install-extension slevesque.shader
code-insiders --install-extension sonarsource.sonarlint-vscode
code-insiders --install-extension spmeesseman.vscode-taskexplorer
code-insiders --install-extension streetsidesoftware.code-spell-checker
code-insiders --install-extension syler.sass-indented
code-insiders --install-extension tamasfe.even-better-toml
code-insiders --install-extension timonwong.shellcheck
code-insiders --install-extension toasty-technologies.octave
code-insiders --install-extension tomwhite007.rename-angular-component
code-insiders --install-extension vinirossa.vscode-gitandgithub-pack
code-insiders --install-extension visualstudioexptteam.intellicode-api-usage-examples
code-insiders --install-extension visualstudioexptteam.vscodeintellicode
code-insiders --install-extension vmware.vscode-boot-dev-pack
code-insiders --install-extension vmware.vscode-spring-boot
code-insiders --install-extension vscjava.vscode-gradle
code-insiders --install-extension vscjava.vscode-java-debug
code-insiders --install-extension vscjava.vscode-java-dependency
code-insiders --install-extension vscjava.vscode-java-pack
code-insiders --install-extension vscjava.vscode-java-test
code-insiders --install-extension vscjava.vscode-maven
code-insiders --install-extension vscjava.vscode-spring-boot-dashboard
code-insiders --install-extension vscjava.vscode-spring-initializr
code-insiders --install-extension wayou.vscode-todo-highlight
code-insiders --install-extension wholroyd.jinja
code-insiders --install-extension wmaurer.change-case
code-insiders --install-extension yuce.erlang-otp
code-insiders --install-extension ziyasal.vscode-open-in-github
